"""create datetime

Revision ID: 372326875cfa
Revises: c87eb8bb0db5
Create Date: 2025-12-13 23:58:53.001039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '372326875cfa'
down_revision: Union[str, None] = 'c87eb8bb0db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance_state', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('balance_state', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balance_state', 'updated_at')
    op.drop_column('balance_state', 'created_at')
    # ### end Alembic commands ###
