"""added models

Revision ID: 6966421e0235
Revises: 
Create Date: 2025-12-17 13:23:14.928570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6966421e0235'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('delta', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_operation_chat_id'), 'balance_operation', ['chat_id'], unique=False)
    op.create_index(op.f('ix_balance_operation_user_id'), 'balance_operation', ['user_id'], unique=False)
    op.create_table('balance_state',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('checks_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('chat_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('balance_state')
    op.drop_index(op.f('ix_balance_operation_user_id'), table_name='balance_operation')
    op.drop_index(op.f('ix_balance_operation_chat_id'), table_name='balance_operation')
    op.drop_table('balance_operation')
    # ### end Alembic commands ###
