"""create balance_state

Revision ID: c87eb8bb0db5
Revises: 
Create Date: 2025-12-13 23:53:09.229924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c87eb8bb0db5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_state',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('checks_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('balance_state')
    # ### end Alembic commands ###
